title: "Rational Agents Lab"
description: "Exploring the logic and limits of intelligent systems."
theme: minima
markdown: kramdown
show_excerpts: true
author: "Shailey Dash"
include:
  - assets/style.css




